In [1]:
import pandas as pd

tab = pd.read_csv("mower_market_snapshot.csv", sep = ";")
#1

tab.head(1400)

capacity  failure_rate     id      margin       price  \
0     10.492623      0.042528  18377  633.766584  828.802103   
1     20.273730      0.037896  19363  731.576817  882.894916   
2     20.190457      0.039111  19641  741.218202  919.355522   
3     27.220131      0.041303  18728  654.255635  817.085097   
4     16.370911      0.037938  18722  703.094527  844.581465   
...         ...           ...    ...         ...         ...   
1394  44.959895      0.234647  18451   63.662561   75.161102   
1395  59.356058      0.253694  18663   64.014543   75.395132   
1396  67.865222      0.228935  19169   62.132035  810.883148   
1397  66.855435      0.244948  18946   58.697122   68.491318   
1398  54.712713      0.177143  19017   64.259212   74.955428   

               prod_cost product_type quality warranty  market_share  \
0     195.03551928211797  auto-portee     Low     3ans      0.006360   
1     151.31809934886763  auto-portee     Low   3 ans.      0.006840   
2     178.13731921134948  auto-portee     Low    3_ans      0.006179   
3     162.82946157588628  auto-portee     Low   3 anss      0.007925   
4     141.48693796090603  auto-portee  Medium    3ans.      0.007406   
...                  ...          ...     ...      ...           ...   
1394  11.498540481074583      essence  Medium     1 an      0.000973   
1395  11.380588736668567      essence     Low     1ans      0.001038   
1396             unknown      essence     Low     1an.      0.001243   
1397   9.794196773761458      essence     Low     1 an      0.001644   
1398  10.696216086742934      essence     Low     1an.      0.001022   

      attractiveness  
0           0.650648  
1           0.699792  
2           0.632129  
3           0.810730  
4           0.757614  
...              ...  
1394        0.513126  
1395        0.547739  
1396        0.655622  
1397        0.867537  
1398        0.538969  

[1399 rows x 11 columns]

In [30]:

print(tab['prod_cost'].describe())

#3



count     1381
unique    1333
top          0
freq        20
Name: prod_cost, dtype: object


In [3]:
(tab['prod_cost'].describe())


(1399,)

In [4]:
tab.fillna(tab.mean())
#5

capacity  failure_rate     id      margin       price  \
0     10.492623      0.042528  18377  633.766584  828.802103   
1     20.273730      0.037896  19363  731.576817  882.894916   
2     20.190457      0.039111  19641  741.218202  919.355522   
3     27.220131      0.041303  18728  654.255635  817.085097   
4     16.370911      0.037938  18722  703.094527  844.581465   
...         ...           ...    ...         ...         ...   
1394  44.959895      0.234647  18451   63.662561   75.161102   
1395  59.356058      0.253694  18663   64.014543   75.395132   
1396  67.865222      0.228935  19169   62.132035  810.883148   
1397  66.855435      0.244948  18946   58.697122   68.491318   
1398  54.712713      0.177143  19017   64.259212   74.955428   

               prod_cost product_type quality warranty  market_share  \
0     195.03551928211797  auto-portee     Low     3ans      0.006360   
1     151.31809934886763  auto-portee     Low   3 ans.      0.006840   
2     178.13731921134948  auto-portee     Low    3_ans      0.006179   
3     162.82946157588628  auto-portee     Low   3 anss      0.007925   
4     141.48693796090603  auto-portee  Medium    3ans.      0.007406   
...                  ...          ...     ...      ...           ...   
1394  11.498540481074583      essence  Medium     1 an      0.000973   
1395  11.380588736668567      essence     Low     1ans      0.001038   
1396             unknown      essence     Low     1an.      0.001243   
1397   9.794196773761458      essence     Low     1 an      0.001644   
1398  10.696216086742934      essence     Low     1an.      0.001022   

      attractiveness  
0           0.650648  
1           0.699792  
2           0.632129  
3           0.810730  
4           0.757614  
...              ...  
1394        0.513126  
1395        0.547739  
1396        0.655622  
1397        0.867537  
1398        0.538969  

[1399 rows x 11 columns]

In [6]:
tab.isnull().sum() #4

capacity           0
failure_rate       0
id                 0
margin             0
price              0
prod_cost         18
product_type       0
quality            0
warranty           0
market_share       0
attractiveness     0
dtype: int64

In [10]:
print(tab["warranty"].unique())
#6

['3ans' '3 ans.' '3_ans' '3 anss' '3ans.' '3 ans' '3_ans.' '3_anss'
 '3anss' '2 ans' '2 anss' '2anss' '2_ans' '2ans' '2_ans.' '2 ans.'
 '2_anss' '2ans.' '1 an' '1an' '1_an.' '1ans' '1an.' '1_ans' '1_an'
 '1 an.' '1 ans']


In [11]:
tab.isnull().len()

AttributeError: 'DataFrame' object has no attribute 'len'

In [14]:
print(tab['prod_cost'].describe())


count     1381
unique    1333
top          0
freq        20
Name: prod_cost, dtype: object


In [17]:
tab['warranty'] = tab['warranty'].str[0]
tab['warranty'] = pd.to_numeric(tab['warranty'])
tab.head()

AttributeError: Can only use .str accessor with string values!

In [18]:
tab["warranty"] = tab["warranty"].str[0].astype(int)
tab["warranty"].unique()

AttributeError: Can only use .str accessor with string values!

In [19]:
tab["warranty"] = tab["warranty"].str[0].astype(int)
tab["warranty"].unique()

AttributeError: Can only use .str accessor with string values!

In [20]:
tab["warranty"].unique()
#8

array([3, 2, 1])

In [21]:
print(tab["warranty"].unique())

[3 2 1]


In [22]:
tab["warranty"] = tab["warranty"].str[0].astype(int)

AttributeError: Can only use .str accessor with string values!

In [23]:
categorie1 = tab[(tab["price"]>0) & (tab["price"]<=300)]
categorie2 = tab[(tab["price"]>=301) & (tab["price"]<=500)]
categorie3 = tab[tab["price"]>=501]
#9

In [24]:
tab.loc[tab["product_type"]=='auto-portee',"product_type"]=1
tab.loc[tab["product_type"]=='electrique',"product_type"]=2
tab.loc[tab["product_type"]=='essence',"product_type"]=3
#10

In [25]:
tab["product_type"].unique()
#10

array([1, 2, 3], dtype=object)

In [26]:
tab["auto-portee"]=0
tab["electrique"]=0
tab["essence"]=0
#11

In [27]:
tab.loc[tab["product_type"]==1,"auto-portee"]=1
tab.loc[tab["product_type"]==2,"electrique"]=1
tab.loc[tab["product_type"]==3,"essence"]=1
#11

In [28]:
tab
#11

capacity  failure_rate     id      margin       price  \
0     10.492623      0.042528  18377  633.766584  828.802103   
1     20.273730      0.037896  19363  731.576817  882.894916   
2     20.190457      0.039111  19641  741.218202  919.355522   
3     27.220131      0.041303  18728  654.255635  817.085097   
4     16.370911      0.037938  18722  703.094527  844.581465   
...         ...           ...    ...         ...         ...   
1394  44.959895      0.234647  18451   63.662561   75.161102   
1395  59.356058      0.253694  18663   64.014543   75.395132   
1396  67.865222      0.228935  19169   62.132035  810.883148   
1397  66.855435      0.244948  18946   58.697122   68.491318   
1398  54.712713      0.177143  19017   64.259212   74.955428   

               prod_cost product_type quality  warranty  market_share  \
0     195.03551928211797            1     Low         3      0.006360   
1     151.31809934886763            1     Low         3      0.006840   
2     178.13731921134948            1     Low         3      0.006179   
3     162.82946157588628            1     Low         3      0.007925   
4     141.48693796090603            1  Medium         3      0.007406   
...                  ...          ...     ...       ...           ...   
1394  11.498540481074583            3  Medium         1      0.000973   
1395  11.380588736668567            3     Low         1      0.001038   
1396             unknown            3     Low         1      0.001243   
1397   9.794196773761458            3     Low         1      0.001644   
1398  10.696216086742934            3     Low         1      0.001022   

      attractiveness  auto-portee  electrique  essence  
0           0.650648            1           0        0  
1           0.699792            1           0        0  
2           0.632129            1           0        0  
3           0.810730            1           0        0  
4           0.757614            1           0        0  
...              ...          ...         ...      ...  
1394        0.513126            0           0        1  
1395        0.547739            0           0        1  
1396        0.655622            0           0        1  
1397        0.867537            0           0        1  
1398        0.538969            0           0        1  

[1399 rows x 14 columns]

In [32]:
 tab = pd.DataFrame(np.array(['prod_cost']))


NameError: name 'np' is not defined

In [33]:
import numpy as np
tab = pd.Series(['prod_cost'])
#2

In [34]:
tab
#2

0    prod_cost
dtype: object